### ISSUE TITLE
デザインの作成

### ISSUE THREAD

**Issue by tomsoyaN** [tomsoyaN/AOJOffline#10]

**Comment by kurikinton105** [comment]
This repository use making design. It use the Modern-UI library,but it can't work perfectly.So please check and commit the code.
[https://github.com/kurikinton105/AOJ_kurikinton/tree/master/ModernUINavigationApp1](https://github.com/kurikinton105/AOJ_kurikinton/tree/master/ModernUINavigationApp1)
